# https://help.github.com/ja/articles/metadata-syntax-for-github-actions
name: Create Project Card Action
description: GitHub actions to create project card.
author: technote-space
inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    required: true
branding:
  # https://feathericons.com/
  icon: 'package'
  color: 'orange'
runs:
  using: node12
  main: lib/main.js
